Repository rhKashif/SteamPulse, pull requests merged in 2023-09, with the labels that each got.

#14 Transform test script and conftest pull request
  pipeline_games/README.md
  pipeline_games/conftest.py
  pipeline_games/load_games.py
  pipeline_games/test_transform.py
  pipeline_games/transform_games.py
Labels: enhancement

#16 automatic schedule working
  setup/main.tf
Labels: enhancement

#19 Created linking tables
  setup/schema.sql
Labels: enhancement

#22 Trailing commas fix
  setup/schema.sql
Labels: bug fix

#23 streamlit ecs service built with terraform
  setup/main.tf
Labels: enhancement

#25 Load script for games
  pipeline_games/extract_games.py
  pipeline_games/load_games.py
  pipeline_games/requirements.txt
  pipeline_games/test_transform.py
  pipeline_games/transform_games.py
Labels: enhancement

#37 actually targetting our ecr with task defs now
  setup/main.tf
  setup/outputs.tf
Labels: bug fix, enhancement

#38 Started a terraform / cloud readme
  setup/README.md
Labels: documentation

#44 READMEs combined
  README.md
  setup/README.md
Labels: documentation

#45 Adding tests for the whole review pipeline
  pipeline_reviews/conftest.py
  pipeline_reviews/extract.py
  pipeline_reviews/pipeline.py
  pipeline_reviews/sentiment.py
  pipeline_reviews/test_extract.py
  pipeline_reviews/test_load.py
  pipeline_reviews/test_sentiment.py
  pipeline_reviews/test_transform.py
Labels: bug fix

#47 Terraform dashboard environment
  README.md
  setup/main.tf
Labels: Cloud Resources

#50 Streamlit theme fixed
  dashboard/Dockerfile
Labels: Visualisation, Cloud Resources

#51 Cleaned .gitignore
  .DS_Store
  .gitignore
Labels: enhancement

#53 fixing failing tests
  pipeline_games/test_extract_games.py
Labels: bug fix, Tests

#57 Correct review tests
  pipeline_reviews/load.py
  pipeline_reviews/pipeline.py
  pipeline_reviews/test_extract.py
  pipeline_reviews/test_load.py
Labels: bug fix, Tests

#60 Added to Readme
  README.md
Labels: enhancement

#64 Dashboard filter bug
  dashboard/pages/community.py
  dashboard/pages/developers.py
  dashboard/pages/releases.py
Labels: bug fix

#71 changed the unique constraint to be in a separate index
  setup/schema.sql
Labels: bug fix, documentation, Cloud Resources

#72 Steam API request error fixing
  pipeline_reviews/extract.py
Labels: bug fix

#73 Update limitations in the review section
  README.md
Labels: documentation

#74 Review count error
  README.md
  pipeline_reviews/extract.py
  pipeline_reviews/transform.py
Labels: bug fix, documentation

#76 added multiprocessing to reviews
  pipeline_reviews/extract.py
Labels: enhancement

#78 Fixing extract tests
  pipeline_reviews/conftest.py
  pipeline_reviews/extract.py
  pipeline_reviews/test_extract.py
  pipeline_reviews/test_transform.py
Labels: Tests

#77 updated big read me
  README.md
  dashboard/README.md
  report/README.md
  report/lambda_function.py
Labels: documentation

#79 Dashboard visualisations
  dashboard/Home.py
  dashboard/pages/community.py
  dashboard/pages/developers.py
  dashboard/pages/releases.py
  dashboard/utility_functions.py
Labels: enhancement, Cloud Resources

#80 Readme editing
  README.md
  dashboard/Dockerfile
Labels: documentation

#82 copied over logo, setup nltk
  dashboard/Dockerfile
Labels: bug fix, Cloud Resources

#83 Streamlit caching
  dashboard/pages/community.py
  dashboard/pages/developers.py
  dashboard/pages/releases.py
  dashboard/pages/subscription.py
  dashboard/utility_functions.py
Labels: enhancement

#86 Modified dimensions on the report to make it more readable
  report/lambda_function.py
Labels: enhancement, Visualisation, Cloud Resources

#84 Dashboard bugs
  dashboard/Dockerfile
  dashboard/Home.py
  dashboard/pages/community.py
  dashboard/pages/developers.py
  dashboard/steampulse_logo.png
  dashboard/utility_functions.py
Labels: bug fix

#89 Inputted label limits for the smaller tables so that title does not overlap with columns next to it
  report/lambda_function.py
Labels: bug fix, Visualisation

#90 Dashboard Sentiment Filtering
  dashboard/utility_functions.py
Labels: bug fix

#91 Load balancer + pipeline bugfix
  setup/main.tf
  setup/outputs.tf
Labels: bug fix, enhancement, Cloud Resources
